Fix lane cycle directory matching
eastgenomics/dx-streaming-upload pull request #10
Opened 2022-06-28 18:25 UTC by jethror1

- Fix for matching run cycle dirs where there are a mix of other files
- switch path for actual run ID in Slack alert
- update to readme commands
![image](https://user-images.githubusercontent.com/45037268/176255492-1f339803-0866-4195-ae18-b1c35577df2b.png)

2022-06-28 18:25 UTC, pep8speaks commented
Hello @jethror1! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`files/notify.py`](https://github.com/eastgenomics/dx-streaming-upload/blob/981b45517e66810350af6642f8557baa440fd064/files/notify.py):

> [Line 179:24](https://github.com/eastgenomics/dx-streaming-upload/blob/981b45517e66810350af6642f8557baa440fd064/files/notify.py#L179): [W605](https://duckduckgo.com/?q=pep8%20W605) invalid escape sequence '\d'
> [Line 179:27](https://github.com/eastgenomics/dx-streaming-upload/blob/981b45517e66810350af6642f8557baa440fd064/files/notify.py#L179): [W605](https://duckduckgo.com/?q=pep8%20W605) invalid escape sequence '\.'
> [Line 179:29](https://github.com/eastgenomics/dx-streaming-upload/blob/981b45517e66810350af6642f8557baa440fd064/files/notify.py#L179): [W605](https://duckduckgo.com/?q=pep8%20W605) invalid escape sequence '\d'
> [Line 180:27](https://github.com/eastgenomics/dx-streaming-upload/blob/981b45517e66810350af6642f8557baa440fd064/files/notify.py#L180): [W605](https://duckduckgo.com/?q=pep8%20W605) invalid escape sequence '\d'
> [Line 180:30](https://github.com/eastgenomics/dx-streaming-upload/blob/981b45517e66810350af6642f8557baa440fd064/files/notify.py#L180): [W605](https://duckduckgo.com/?q=pep8%20W605) invalid escape sequence '\.'
> [Line 180:32](https://github.com/eastgenomics/dx-streaming-upload/blob/981b45517e66810350af6642f8557baa440fd064/files/notify.py#L180): [W605](https://duckduckgo.com/?q=pep8%20W605) invalid escape sequence '\d'

2022-06-29 10:41 UTC, JasonLing95 requested changes
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/dx-streaming-upload/10)* status: all files reviewed, 1 unresolved discussion (waiting on @jethror1)

*[a discussion](https://reviewable.io/reviews/eastgenomics/dx-streaming-upload/10#-N5j1znZ754vcsfTknkh:-N5j1znZ754vcsfTknki:b-vds9gh) (no related file):*
@jethror1 Hey, I've been looking at the Dockerfile for a bit, is it right that you want the user dx-upload as the default user in the container?

___


<!-- Sent from Reviewable.io -->

2022-06-29 10:52 UTC, jethror1 commented
yeah that's intentional, for us I'm running it as root user due to fun permissions issues with red hat and accessing host data as it was easier, for others running Ubuntu etc the dx-upload user can be used. It gives the option of a non-root user in the container with a specified uuid others can use.

If you do `docker run` with specifying a user it will default to root as we want, but can use `--user dx-upload` to run it with that user

2022-06-29 10:55 UTC, JasonLing95 approved these changes
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/dx-streaming-upload/10)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jethror1)



<!-- Sent from Reviewable.io -->

2022-06-29 10:55 UTC, merged